Config = {}

Config.Fortunes = {
    
    "Someone is looking up to you. Don't let that person down.",
    "Never forget that a half truth is a whole lie.",
    "No snowflake in an avalanche ever feels responsible.",
    "Your heart will skip a beat.",
    "Don't be afraid to take that big step.",
    "A passionate romance will appear in your life when you least expect it.",
    "You will marry a professional athlete - if competitive eating is considered a sport.",
    "Ask not what your fortune cookie can do for you, but what you can do for your fortune cookie.",
    "Enjoy yourself while you can.",
    "I see money in your future... but it is not yours!",
    "Three can keep a secret, if you get rid of two.",
    "Your efforts have not gone unnoticed.",
    "Avoid taking unnecessary gambles.",
    "Why not treat yourself to a good time, instead of waiting for someone else to do it?",
    "I hear Guarma is great this time of the year.",
    "I see a trip to Mexico in your future.",
    "A good way to stay healthy is eating more Chinese food. Try a dumpling!",
    "A close friend reveals a hidden talent.",
    "Comfort zones are most often expanded through discomfort.",
    "If you pull your head out of your ass your life won't be so shitty.",
    "Be cautious of walking in darkness alone.",
    "Your fortune said you need to make a donation. Give it to the chef. ",
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "A little impatience will spoil great plans.",
    "A smile will gain you ten more years of life.",
    "A bird does not sing because it has an answer. It sings because it has a song.",
    "Talk does not cook rice.",
    "A man who cannot tolerate small misfortunes can never accomplish great things.",
    "Even a hare will bite when it is cornered.",
    "The best time to plant a tree was 20 years ago. The second best time is today.",
    "If you want to find out about the road ahead, then ask about it from those coming back.",
    "Patience is your alley at the moment. Don’t worry!",
    "Nothing is impossible to a St. Denis resident!",
    "A ship in harbor is safe, but that’s not why ships are built.",
    "You don’t need strength to let go of something. What you really need is a good lawyer.",
    "He who throws mud loses ground and lives in Valentine.",
    "Big journeys begin with farming.",
    "People learn little from success, but much from failure.",
    "The best way to get rid of an enemy is to make a friend.",
    "People are naturally attracted to you.",
    "Your shoes will make you happy today.",
    "The man or woman you desire feels the same about you.",
    "A very attractive person in New Austin has a message for you.",
    "A short stranger from Rhodes will soon enter your life with blessings to share.",
    "Treasure awaits you in a cave to the west.",
    "A wise man in Saint Denis will invite you to a party south of the border",
    "Dumplings and milk are a weak man's best friend. ",
    "Unlucky. Get another fortune cookie.",

}